defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *defaults
  database: ex3_development

test: &test
  <<: *defaults
  database: ex3_test

production:
  <<: *defaults
  database: ex3_production

cucumber:
  <<: *test