defaults: &defaults
  host: localhost:3000
  session_secret: 'cf3da036009f0ec4220f3996ef7f79617fdce01f577117e0a21d074a3d2490eeaa983337f07859d048780d4fdee50bfce22ac2f87e27a5d54c68f9ac4d4d7059'
  facebook:
    app_key: '274790155904059'
    secret: 'aa3dc1b647378b4fdd096234751afc51'
    options: {scope: 'user_likes,user_birthday,user_location,user_relationships,friends_birthday,friends_likes,friends_interests,email,publish_actions'}
  twitter:
    consumer_key: 'Wmg5IdN6FY8692YIO7whJA'
    consumer_secret: 'q0SiLioJ2e7Ym8mFpea3icTZVnbSD1A9Izw23JMD4A'
  aws:
    access_key_id: 
    secret_access_key: 

development:
  <<: *defaults

test: &test
  <<: *defaults
  host: test.host

production:
  <<: *defaults
  host: production.host

quality:
  <<: *defaults
  host: quality.executter.com

cucumber:
  <<: *test